version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: prueba_tecnica
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: JhonDoe
      POSTGRES_PASSWORD: SecretKey
      POSTGRES_DB: api_test
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
