version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: prueba_tecnica
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${ENV_USER}
      POSTGRES_PASSWORD: ${ENV_PASSWORD}
      POSTGRES_DB: ${ENV_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
